"""集中定义所有错误码 — 便于 grep"""

# ---- Prediction Domain ----
PREDICTION_NOT_FOUND = "PREDICTION_NOT_FOUND"
PREDICTION_EXISTS = "PREDICTION_EXISTS"
BLIND_VIOLATION_SEEN_DATA = "BLIND_VIOLATION_SEEN_DATA"

# ---- Rubric Domain ----
RUBRIC_LEAK_DETECTED = "RUBRIC_LEAK_DETECTED"
BUMP_INSUFFICIENT_SAMPLES = "BUMP_INSUFFICIENT_SAMPLES"

# ---- LLM Domain ----
LLM_CALL_FAILED = "LLM_CALL_FAILED"
LLM_JSON_PARSE_FAILED = "LLM_JSON_PARSE_FAILED"

# ---- Script Domain ----
SCRIPT_NOT_FOUND = "SCRIPT_NOT_FOUND"

# ---- Benchmark Domain ----
BENCHMARK_NOT_FOUND = "BENCHMARK_NOT_FOUND"

# ---- CLI Domain ----
CHEAT_CLI_NOT_FOUND = "CHEAT_CLI_NOT_FOUND"
CHEAT_CLI_FAILED = "CHEAT_CLI_FAILED"

# ---- Init Domain ----
INIT_ALREADY_INITIALIZED = "INIT_ALREADY_INITIALIZED"

# ---- Persona Domain ----
PERSONA_NOT_FOUND = "PERSONA_NOT_FOUND"

# ---- Migration Domain ----
MIGRATION_FAILED = "MIGRATION_FAILED"

# ---- Notification Domain ----
NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"

# ---- Experiment Domain ----
EXPERIMENT_NOT_FOUND = "EXPERIMENT_NOT_FOUND"

# ---- Monitor Domain ----
MONITOR_NOT_FOUND = "MONITOR_NOT_FOUND"

# ---- Comments Fetch Domain ----
COMMENTS_FETCH_FAILED = "COMMENTS_FETCH_FAILED"

# ---- General ----
FILE_NOT_FOUND = "FILE_NOT_FOUND"
INVALID_REQUEST = "INVALID_REQUEST"

# ---- Auth Domain （新增）----
AUTH_REGISTRATION_CLOSED = "AUTH_REGISTRATION_CLOSED"
AUTH_EMAIL_EXISTS = "AUTH_EMAIL_EXISTS"
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
AUTH_INVALID_INVITE_CODE = "AUTH_INVALID_INVITE_CODE"
AUTH_INVITE_CODE_EXHAUSTED = "AUTH_INVITE_CODE_EXHAUSTED"
AUTH_INVITE_CODE_REQUIRED = "AUTH_INVITE_CODE_REQUIRED"

# ---- Points Domain （新增）----
POINTS_INSUFFICIENT = "POINTS_INSUFFICIENT"
